CREATE TABLE IF NOT EXISTS `user`(
    `user_id` INT PRIMARY KEY AUTO_INCREMENT,
    `username` VARCHAR(20) UNIQUE NOT NULL,
    `password` VARCHAR(120) NOT NULL,
    `active` BOOL DEFAULT TRUE
) ENGINE = MYISAM;

CREATE TABLE IF NOT EXISTS `notes`(
    `note_id` INT PRIMARY KEY AUTO_INCREMENT,
    `user_id` INT,
    `title` VARCHAR(100) NOT NULL,
    `content` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    `active` BOOL DEFAULT TRUE
) ENGINE = MYISAM;